### ISSUE TITLE
docker0 issues

### ISSUE THREAD

**Issue by techcubs** [tirtadji-com/rpi_debian_ha_supervised#2]
Thanks for the guide, I installed Home assistant supervised on Raspberry Pi 4. 

When I look at the console output, i keep getting these errors:

Sep 07 18:54:16 Home-Assistant kernel: docker0: port 1(veth32dfd0f) entered forwarding state
Sep 07 18:54:22 Home-Assistant kernel: docker0: port 1(veth32dfd0f) entered disabled state
Sep 07 18:54:22 Home-Assistant kernel: docker0: port 1(veth32dfd0f) entered disabled state
Sep 07 18:54:22 Home-Assistant kernel: docker0: port 1(veth32dfd0f) entered disabled state
Sep 07 18:54:29 Home-Assistant kernel: docker0: port 1(veth06cabd2) entered blocking state
Sep 07 18:54:29 Home-Assistant kernel: docker0: port 1(veth06cabd2) entered disabled state
Sep 07 18:54:29 Home-Assistant kernel: docker0: port 1(veth06cabd2) entered blocking state
Sep 07 18:54:29 Home-Assistant kernel: docker0: port 1(veth06cabd2) entered forwarding state
Sep 07 18:54:35 Home-Assistant kernel: docker0: port 1(veth06cabd2) entered disabled state
Sep 07 18:54:35 Home-Assistant kernel: docker0: port 1(veth06cabd2) entered disabled state
Sep 07 18:54:35 Home-Assistant kernel: docker0: port 1(veth06cabd2) entered disabled state
Sep 07 18:54:42 Home-Assistant kernel: docker0: port 1(vetha4d3529) entered blocking state
Sep 07 18:54:42 Home-Assistant kernel: docker0: port 1(vetha4d3529) entered disabled state
Sep 07 18:54:42 Home-Assistant kernel: docker0: port 1(vetha4d3529) entered blocking state
Sep 07 18:54:42 Home-Assistant kernel: docker0: port 1(vetha4d3529) entered forwarding state

any ideas on how to rectify this ?

**Comment by ranrinc** [comment]
I have not implemented my script for a while, let me restest it again. Can you give me more detail on how you do it? and where does the script stop?

**Comment by ranrinc** [comment]
This problem is fixed. So please try again and make sure you are downloading Debian 11 and not Debian 10

**Comment by Victripper** [comment]
Still getting the same on RPI4 8GB with USB external drive

using

2021.08.23 | 11 (Bullseye) | 4 | p400 | xz-compressed image 349.82 MB, 2021-08-23 12:48:-0500sha256sumGPG-signed sha256sum
-- | -- | -- | -- | --

**Comment by ranrinc** [comment]
> Still getting the same on RPI4 8GB with USB external drive
> 
> using
> 
> 2021.08.23	11 (Bullseye)	4	p400	xz-compressed image 349.82 MB, 2021-08-23 12:48:-0500sha256sumGPG-signed sha256sum

you are running RPI4 8GB or you are running P400? If you are running RPI4 then you are using the wrong img? I double test the script and it works.

I'm making flow changes and clean some of the unnecessary flow and it should work. Test it on my RPI4 8GB and working like a charm.

**Comment by Victripper** [comment]
That probably is my issue.. Sorry for my stuff up.  I will use the correct image

**Comment by Victripper** [comment]
Yes Completely fixed my issue.

**Comment by ranrinc** [comment]
> Yes Completely fixed my issue.

Great.. I'm working on a better installer so stay tuned.
